### PR TITLE
Use bank tx ID's for import ID

### PR DESCRIPTION
**Pull request by thomaspurchas**
Use the tx ID's provided by each bank for the import ID. This should prevent duplicate tx's from being created.

### CODE REVIEW

**Comment by scottrobertson** [comment]
Hey

Thanks!

I need to think about this a bit more, as we also need to think about how this impacts CSV imports, as they do not have an ID available (this is why we generate our own ID. We did used to use the bank ids but removed it for a number of reasons - most of which i cannot remember now).

**Comment by scottrobertson** [comment]
I think we also had issues with import_id length. One of the banks id format was too long.

**Comment by thomaspurchas** [comment]
The CSV import makes sense, I figured that people should just use the importer in this project, rather than CSVs. Seems strange to want to chop and change your import method.

As for the import_id length, I can tell you that Monzo's one is working fine for me at the moment. I no longer have a Starling account so can't test.

**Comment by scottrobertson** [comment]
I agree about the CSV stuff. I will test the lengths of Starling and Teller and get this merged.

I will tag a new release, and warn people that the id format has changed so they will end up with duplicates that they need to merge.

**Comment by scottrobertson** [comment]
Yeah, so the import_id has to be 36 chars or less. Starling's are 36 chars (UUID).

So we can either truncate with a "STARLING" prefix, or just not have a prefix....

**Pull request closed without merging**
